package usecase

import (
	"context"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/koshuang/trello-ai-orchestrator/config"
	"github.com/koshuang/trello-ai-orchestrator/domain"
)

type WebhookInteractor struct {
	cfg           *config.Config
	stateRepo     WorkflowStateRepository
	eventRepo     ProcessedEventRepository
	trelloGateway TrelloGateway
	githubGateway GitHubGateway
	llmGateway    LLMGateway
}

func NewWebhookInteractor(
	cfg *config.Config,
	stateRepo WorkflowStateRepository,
	eventRepo ProcessedEventRepository,
	trelloGateway TrelloGateway,
	githubGateway GitHubGateway,
	llmGateway LLMGateway,
) *WebhookInteractor {
	return &WebhookInteractor{
		cfg:           cfg,
		stateRepo:     stateRepo,
		eventRepo:     eventRepo,
		trelloGateway: trelloGateway,
		githubGateway: githubGateway,
		llmGateway:    llmGateway,
	}
}

func (w *WebhookInteractor) ProcessEvent(ctx context.Context, payload *domain.TrelloWebhookPayload) error {
	action := payload.Action
	actionID := action.ID
	cardID := action.Data.Card.ID
	eventType := action.Type
	creatorID := action.MemberCreator.ID
	creatorUsername := action.MemberCreator.Username

	log.Printf("[Orchestrator] Processing event %s, type=%s, card=%s, user=%s", actionID, eventType, cardID, creatorUsername)

	if cardID == "" {
		log.Printf("[Orchestrator] Skipped: missing card ID in event %s", actionID)
		return nil
	}

	// 1. Bot Filtering
	for _, botID := range w.cfg.BotTrelloMemberIDs {
		if creatorID == botID || creatorUsername == botID {
			log.Printf("[Orchestrator] Ignored: event generated by bot user %s (%s)", creatorUsername, creatorID)
			return nil
		}
	}

	// 2. Idempotency Check
	exists, err := w.eventRepo.Exists(ctx, "trello", actionID)
	if err != nil {
		return fmt.Errorf("failed to check event idempotency: %w", err)
	}
	if exists {
		log.Printf("[Orchestrator] Skipped: event %s already processed", actionID)
		return nil
	}

	// 3. Load Workflow State
	state, err := w.stateRepo.GetByCardID(ctx, cardID)
	if err != nil {
		return fmt.Errorf("failed to retrieve workflow state: %w", err)
	}

	isNewState := false
	if state == nil {
		isNewState = true
		state = &domain.WorkflowState{
			TrelloCardID:          cardID,
			TrelloCardTitle:       action.Data.Card.Name,
			TrelloCardURL:         fmt.Sprintf("https://trello.com/c/%s", action.Data.Card.ShortLink),
			Status:                domain.StatusNew,
			LastProcessedActionID: actionID,
			CreatedAt:             time.Now(),
			UpdatedAt:             time.Now(),
		}
	}

	// 4. Fetch full Trello card context
	cardContext, err := w.trelloGateway.FetchCardContext(ctx, cardID)
	if err != nil {
		// Log error but we can try to proceed if we have basic details,
		// though fetching card context is usually required.
		return fmt.Errorf("failed to fetch Trello card context: %w", err)
	}

	// Sync Trello card URL & title from context if they match
	if cardContext.URL != "" {
		state.TrelloCardURL = cardContext.URL
	}
	if cardContext.Title != "" {
		state.TrelloCardTitle = cardContext.Title
	}

	// If there's an AI state block in description, parse it to merge with state
	aiStateBlock := ParseAIState(cardContext.Description)
	if aiStateBlock != nil {
		cardContext.AIState = aiStateBlock
		// Merging GitHub url if DB state doesn't have it yet
		if state.GitHubIssueURL == "" && aiStateBlock.GitHubIssue != "" {
			state.GitHubIssueURL = aiStateBlock.GitHubIssue
			// Extract number from url if possible
			state.GitHubIssueNumber = extractIssueNumber(aiStateBlock.GitHubIssue)
		}
		if state.PlanPath == "" && aiStateBlock.Plan != "" {
			state.PlanPath = aiStateBlock.Plan
		}
		if isNewState && aiStateBlock.Status != "" {
			state.Status = domain.WorkflowStatus(aiStateBlock.Status)
		}
	}

	// 5. @mention filtering — skip LLM call if no bot is @mentioned
	commentText := action.Data.Text
	if len(w.cfg.BotTrelloMemberIDs) > 0 && !containsMention(commentText, w.cfg.BotTrelloMemberIDs) {
		log.Printf("[Orchestrator] Ignored: comment does not @mention any bot user. Marking event as success.")
		_ = w.eventRepo.Create(ctx, &domain.ProcessedEvent{
			ID:           "trello-" + actionID,
			Provider:     "trello",
			EventID:      actionID,
			TrelloCardID: cardID,
			EventType:    eventType,
			ProcessedAt:  time.Now(),
			Status:       "success",
		})
		return nil
	}

	// 6. Run Decision Engine
	rules := getOperatingRules()
	llmInput := &domain.LLMInput{
		NewComment:     commentText,
		CardContext:    *cardContext,
		WorkflowState:  *state,
		OperatingRules: rules,
	}

	decision, err := w.llmGateway.Decide(ctx, llmInput)
	if err != nil {
		// Update event with failed status but do not save state
		_ = w.eventRepo.Create(ctx, &domain.ProcessedEvent{
			ID:           "trello-" + actionID,
			Provider:     "trello",
			EventID:      actionID,
			TrelloCardID: cardID,
			EventType:    eventType,
			ProcessedAt:  time.Now(),
			Status:       "failed",
			Error:        err.Error(),
		})
		return fmt.Errorf("llm decision engine failed: %w", err)
	}

	log.Printf("[Orchestrator] Decision received: Action=%s, Reason=%s", decision.Action, decision.Reason)

	// 6. Execute Actions (Respecting Safe Mode)
	var actionErr error

	// Handle Reply Comment
	if decision.Action == "reply_comment" && decision.ReplyComment != "" {
		if w.cfg.AutoReplyEnabled {
			log.Printf("[Orchestrator] Posting reply comment to Trello card %s", cardID)
			actionErr = w.trelloGateway.AddComment(ctx, cardID, decision.ReplyComment)
		} else {
			log.Printf("[Orchestrator] [SAFE MODE] Skip Trello comment write. Draft: %q", decision.ReplyComment)
		}
	}

	// Handle GitHub Issue Creation/Link
	if decision.Action == "create_github_issue" && decision.GitHubIssue != nil && actionErr == nil {
		// Verify if we already have a GitHub issue URL to prevent duplicate creation
		if state.GitHubIssueURL == "" {
			// Scan Trello context attachments for github link as fallback
			foundGitURL := ""
			for _, attach := range cardContext.Attachments {
				if strings.Contains(attach.URL, "github.com/") && strings.Contains(attach.URL, "/issues/") {
					foundGitURL = attach.URL
					break
				}
			}

			if foundGitURL != "" {
				log.Printf("[Orchestrator] GitHub issue already linked via attachments: %s", foundGitURL)
				state.GitHubIssueURL = foundGitURL
				state.GitHubIssueNumber = extractIssueNumber(foundGitURL)
			} else if w.cfg.AutoCreateGitHubIssue {
				log.Printf("[Orchestrator] Creating new GitHub issue: %s", decision.GitHubIssue.Title)
				issuePayload := &domain.GitHubIssuePayload{
					Title:  decision.GitHubIssue.Title,
					Body:   decision.GitHubIssue.Body,
					Labels: decision.GitHubIssue.Labels,
				}
				issueResp, err := w.githubGateway.CreateIssue(ctx, issuePayload)
				if err != nil {
					actionErr = fmt.Errorf("failed to create github issue: %w", err)
				} else {
					state.GitHubIssueURL = issueResp.HTMLURL
					state.GitHubIssueNumber = issueResp.Number
					log.Printf("[Orchestrator] GitHub issue created: %s", issueResp.HTMLURL)
				}
			} else {
				log.Printf("[Orchestrator] [SAFE MODE] Skip GitHub issue creation. Proposed Title: %q", decision.GitHubIssue.Title)
			}
		} else {
			log.Printf("[Orchestrator] GitHub issue already linked in state: %s", state.GitHubIssueURL)
		}
	}

	// Handle GitHub Issue Update
	if decision.Action == "update_github_issue" && decision.GitHubIssue != nil && state.GitHubIssueNumber > 0 && actionErr == nil {
		if w.cfg.AutoCreateGitHubIssue {
			log.Printf("[Orchestrator] Updating GitHub issue #%d: %s", state.GitHubIssueNumber, decision.GitHubIssue.Title)
			issuePayload := &domain.GitHubIssuePayload{
				Title:  decision.GitHubIssue.Title,
				Body:   decision.GitHubIssue.Body,
				Labels: decision.GitHubIssue.Labels,
			}
			err := w.githubGateway.UpdateIssue(ctx, state.GitHubIssueNumber, issuePayload)
			if err != nil {
				actionErr = fmt.Errorf("failed to update github issue #%d: %w", state.GitHubIssueNumber, err)
			}
		} else {
			log.Printf("[Orchestrator] [SAFE MODE] Skip GitHub issue #%d update.", state.GitHubIssueNumber)
		}
	}

	// Handle Plan Creation/Update
	if (decision.Action == "create_plan" || decision.Action == "update_plan") && decision.Plan != nil && actionErr == nil {
		planPath := decision.Plan.Path
		if planPath == "" {
			slug := slugify(state.TrelloCardTitle)
			planPath = fmt.Sprintf("docs/plans/trello-%s-%s.md", cardID, slug)
		}

		if w.cfg.AutoCreatePlan {
			log.Printf("[Orchestrator] Writing implementation plan to: %s", planPath)
			actionErr = writePlanFile(planPath, decision.Plan.Content)
			if actionErr == nil {
				state.PlanPath = planPath
			}
		} else {
			log.Printf("[Orchestrator] [SAFE MODE] Skip writing implementation plan to disk. Proposed path: %s", planPath)
			state.PlanPath = planPath // Record proposed path in database state
		}
	}

	if actionErr != nil {
		log.Printf("[Orchestrator] Failed executing actions: %v", actionErr)
		// We still record the event as failed to allow retry, but don't commit state
		_ = w.eventRepo.Create(ctx, &domain.ProcessedEvent{
			ID:           "trello-" + actionID,
			Provider:     "trello",
			EventID:      actionID,
			TrelloCardID: cardID,
			EventType:    eventType,
			ProcessedAt:  time.Now(),
			Status:       "failed",
			Error:        actionErr.Error(),
		})
		return actionErr
	}

	// 7. Update State Fields
	state.Status = domain.WorkflowStatus(decision.StateUpdate.Status)
	state.LastProcessedActionID = actionID
	state.Summary = decision.StateUpdate.Summary
	state.CurrentUnderstanding = decision.StateUpdate.CurrentUnderstanding
	state.Decisions = decision.StateUpdate.Decisions
	state.OpenQuestions = decision.StateUpdate.OpenQuestions
	state.NextAction = decision.StateUpdate.NextAction
	state.UpdatedAt = time.Now()

	// Update Trello Card Description if we are allowed to write
	if w.cfg.AutoReplyEnabled || w.cfg.AutoCreateGitHubIssue { // If either write flag is enabled, we sync desc
		newDesc := UpdateDescriptionWithAIState(cardContext.Description, state)
		if newDesc != cardContext.Description {
			log.Printf("[Orchestrator] Syncing updated AI State to Trello Card Description")
			err = w.trelloGateway.UpdateCardDescription(ctx, cardID, newDesc)
			if err != nil {
				log.Printf("[Orchestrator] Warning: failed to sync Trello card description: %v", err)
				// We do not fail the overall transaction if description sync fails
			}
		}
	} else {
		proposedDesc := UpdateDescriptionWithAIState(cardContext.Description, state)
		log.Printf("[Orchestrator] [SAFE MODE] Skip Trello card description update. Proposed content preview:\n%s", proposedDesc)
	}

	// 8. Commit Workflow State to Repository
	err = w.stateRepo.Save(ctx, state)
	if err != nil {
		return fmt.Errorf("failed to save updated workflow state: %w", err)
	}

	// 9. Mark Event as Processed (Success)
	err = w.eventRepo.Create(ctx, &domain.ProcessedEvent{
		ID:           "trello-" + actionID,
		Provider:     "trello",
		EventID:      actionID,
		TrelloCardID: cardID,
		EventType:    eventType,
		ProcessedAt:  time.Now(),
		Status:       "success",
	})
	if err != nil {
		return fmt.Errorf("failed to record processed event: %w", err)
	}

	log.Printf("[Orchestrator] Successfully completed event %s", actionID)
	return nil
}

// Utility to parse GitHub issue number from URL
func extractIssueNumber(url string) int {
	re := regexp.MustCompile(`/issues/(\d+)`)
	matches := re.FindStringSubmatch(url)
	if len(matches) > 1 {
		var num int
		_, err := fmt.Sscanf(matches[1], "%d", &num)
		if err == nil {
			return num
		}
	}
	return 0
}

func containsMention(comment string, botUsernames []string) bool {
	lower := strings.ToLower(comment)
	for _, bot := range botUsernames {
		botLower := strings.ToLower(strings.TrimSpace(bot))
		if botLower == "" {
			continue
		}
		mention := "@" + botLower
		if strings.Contains(lower, mention) {
			return true
		}
	}
	return false
}

// Utility to write plan file
func writePlanFile(path, content string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0644)
}

// Simple slugify for filenames
func slugify(s string) string {
	s = strings.ToLower(s)
	s = strings.ReplaceAll(s, " ", "-")
	reg := regexp.MustCompile("[^a-z0-9_-]")
	s = reg.ReplaceAllString(s, "")
	if len(s) > 30 {
		s = s[:30]
	}
	return strings.Trim(s, "-")
}

func getOperatingRules() string {
	return `
Operating Rules:
1. Claude Run context is disposable. Read the database Workflow State as the primary machine-readable state.
2. If PM asks a simple clarification and enough context exists, draft a reply.
3. If requirement is ambiguous, ask a concise clarification question.
4. If engineering work is implied but no issue exists, propose "create_github_issue".
5. If Kos explicitly gives instruction in a comment, treat it as high priority and follow it.
6. If unsure, set action to "ask_kos" or "update_state_only", not risky execution.
7. If the comment only says thanks / ack / done, set action to "update_state_only" or "ignore".
`
}
